version: '3.7'

services:
  github_data_service:
    build:
      context: ./
      dockerfile: github_data_service/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - github_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - github_network

  auth_service:
    build:
      context: ./
      dockerfile: auth_service/Dockerfile
    env_file:
      - ./env_files/auth.env
    environment:
      - HOST=0.0.0.0
      - PORT=8081
    ports: 
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    env_file:
      - ./env_files/mongo.env
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  github_network:
    driver: bridge
  app_network:
    driver: bridge

volumes:
  mongo_data:
