version: '3.7'

services:
  github_data_service:
    build:
      context: ./
      dockerfile: github_data_service/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - zest_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - zest_network

networks:
  zest_network:
    driver: bridge
