version: '3.7'

services:
  # Responsible for retrieving data from Github API
  github_data_service:
    build:
      context: ./
      dockerfile: github_data_service/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app_network
    
  # Responsible for managing user's authentication
  auth_service:
    build:
      context: ./
      dockerfile: auth_service/Dockerfile
    env_file:
      - ./env_files/secrets.env
    environment:
      - HOST=0.0.0.0
      - PORT=8081
    ports: 
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - app_network

  # Responsible for managing user's favorites
  favorites_service:
    build:
      context: ./
      dockerfile: user_favorites_service/Dockerfile
    env_file:
      - ./env_files/secrets.env
    environment:
      - HOST=0.0.0.0
      - PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - github_data_service
      - auth_service
    networks:
      - app_network
  
  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    env_file:
      - ./env_files/mongo.env
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
