openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login endpoint
      description: |
        Logs in a user with the provided email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  jwt_token:
                    type: string
        400:
          description: Missing email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        401:
          description: User does not exist or password and email do not match
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /signup:
    post:
      summary: Signup endpoint
      description: |
        Signs up a new user with the provided email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  jwt_token:
                    type: string
        400:
          description: Missing email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        409:
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
